name: ccb_skimage
channels:
  - conda-forge
dependencies:
  - python >= 3.9
  - numpy >= 1.22
  - scipy >= 1.5
  - matplotlib >= 3.0
  - scikit-image >= 0.18
  - notebook >= 4.0
  - itk >= 5.0
  - itkwidgets >= 0.30
