name: ccb_skimage
channels:
  - conda-forge
dependencies:
  - python >= 3.7
  - numpy >= 1.12
  - scipy >= 1.0
  - matplotlib >= 2.1
  - scikit-image >= 0.18
  - notebook >= 4.0
  - itk >= 5.0
  - itkwidgets >= 0.18
